{
 "title": "Meshtastic",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Radios",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_latitude", "legendFormat": "__auto" },
    { "expr": "node_longitude", "legendFormat": "__auto" },
    { "expr": "node_hop_limit", "legendFormat": "__auto" },
    { "expr": "node_info", "legendFormat": "__auto" },
    { "expr": "node_altitude", "legendFormat": "__auto" },
    { "expr": "node_hop_count", "legendFormat": "__auto" },
    { "expr": "node_rssi", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spotted radios",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (num) (node_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radios with location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (num) (node_latitude))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(message_count_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(type) (rate(message_count_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Strongest signal (direct connections)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "topk(50, node_snr)", "legendFormat": "__auto" },
    { "expr": "node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hop count by node",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    { "expr": "node_hop_count", "legendFormat": "__auto" },
    { "expr": "node_info", "legendFormat": "__auto" }
   ]
  }
 ]
}